name: timed_config
version: 0.1.0
authors:
  - Winton Welsh
email: mail@wintoni.us
homepage: http://github.com/winton/timed_config
summary: Starts a thread that loads a YAML config every X minutes
description: Starts a thread that loads a YAML config every X minutes
dependencies: null
development_dependencies: null